### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by vkyeswa** [CViniciusSDias/google-crawler#1]
ErrorException in KProxy.php line 64:
Undefined index: q
When i use a sentence search term "Hello how are you"

**Comment by CViniciusSDias** [comment]
Which server number were you using? I am trying to reproduce the error in my PC but I'm not being able.

**Comment by vkyeswa** [comment]
3

**Comment by CViniciusSDias** [comment]
Thank you, @vkyeswa 

The problem was at parsing a google book suggestion. Just as it's done with images and videos, this kind of result now throws an InvalidResultException.
